kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go build

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "103.23.44.17" ]
    source: ./*
    target: /mnt
    key:
      from_secret: ssh_rsa
    recursive: true
    script:
      - ls /mnt

